/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedPrsRouteImport } from './routes/_authenticated/prs'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSettingsReposRouteImport } from './routes/_authenticated/settings/repos'
import { Route as AuthenticatedSettingsClisRouteImport } from './routes/_authenticated/settings/clis'
import { Route as AuthenticatedPrsPrIdRouteImport } from './routes/_authenticated/prs.$prId'
import { Route as AuthenticatedPrsPrIdReviewsReviewIdRouteImport } from './routes/_authenticated/prs.$prId.reviews.$reviewId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrsRoute = AuthenticatedPrsRouteImport.update({
  id: '/prs',
  path: '/prs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsReposRoute =
  AuthenticatedSettingsReposRouteImport.update({
    id: '/repos',
    path: '/repos',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsClisRoute =
  AuthenticatedSettingsClisRouteImport.update({
    id: '/clis',
    path: '/clis',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedPrsPrIdRoute = AuthenticatedPrsPrIdRouteImport.update({
  id: '/$prId',
  path: '/$prId',
  getParentRoute: () => AuthenticatedPrsRoute,
} as any)
const AuthenticatedPrsPrIdReviewsReviewIdRoute =
  AuthenticatedPrsPrIdReviewsReviewIdRouteImport.update({
    id: '/reviews/$reviewId',
    path: '/reviews/$reviewId',
    getParentRoute: () => AuthenticatedPrsPrIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/history': typeof AuthenticatedHistoryRoute
  '/prs': typeof AuthenticatedPrsRouteWithChildren
  '/prs/$prId': typeof AuthenticatedPrsPrIdRouteWithChildren
  '/settings/clis': typeof AuthenticatedSettingsClisRoute
  '/settings/repos': typeof AuthenticatedSettingsReposRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/prs/$prId/reviews/$reviewId': typeof AuthenticatedPrsPrIdReviewsReviewIdRoute
}
export interface FileRoutesByTo {
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/history': typeof AuthenticatedHistoryRoute
  '/prs': typeof AuthenticatedPrsRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/prs/$prId': typeof AuthenticatedPrsPrIdRouteWithChildren
  '/settings/clis': typeof AuthenticatedSettingsClisRoute
  '/settings/repos': typeof AuthenticatedSettingsReposRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/prs/$prId/reviews/$reviewId': typeof AuthenticatedPrsPrIdReviewsReviewIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/prs': typeof AuthenticatedPrsRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/prs/$prId': typeof AuthenticatedPrsPrIdRouteWithChildren
  '/_authenticated/settings/clis': typeof AuthenticatedSettingsClisRoute
  '/_authenticated/settings/repos': typeof AuthenticatedSettingsReposRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/prs/$prId/reviews/$reviewId': typeof AuthenticatedPrsPrIdReviewsReviewIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/history'
    | '/prs'
    | '/prs/$prId'
    | '/settings/clis'
    | '/settings/repos'
    | '/settings/'
    | '/prs/$prId/reviews/$reviewId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/history'
    | '/prs'
    | '/'
    | '/prs/$prId'
    | '/settings/clis'
    | '/settings/repos'
    | '/settings'
    | '/prs/$prId/reviews/$reviewId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/history'
    | '/_authenticated/prs'
    | '/_authenticated/'
    | '/_authenticated/prs/$prId'
    | '/_authenticated/settings/clis'
    | '/_authenticated/settings/repos'
    | '/_authenticated/settings/'
    | '/_authenticated/prs/$prId/reviews/$reviewId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prs': {
      id: '/_authenticated/prs'
      path: '/prs'
      fullPath: '/prs'
      preLoaderRoute: typeof AuthenticatedPrsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/repos': {
      id: '/_authenticated/settings/repos'
      path: '/repos'
      fullPath: '/settings/repos'
      preLoaderRoute: typeof AuthenticatedSettingsReposRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/clis': {
      id: '/_authenticated/settings/clis'
      path: '/clis'
      fullPath: '/settings/clis'
      preLoaderRoute: typeof AuthenticatedSettingsClisRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/prs/$prId': {
      id: '/_authenticated/prs/$prId'
      path: '/$prId'
      fullPath: '/prs/$prId'
      preLoaderRoute: typeof AuthenticatedPrsPrIdRouteImport
      parentRoute: typeof AuthenticatedPrsRoute
    }
    '/_authenticated/prs/$prId/reviews/$reviewId': {
      id: '/_authenticated/prs/$prId/reviews/$reviewId'
      path: '/reviews/$reviewId'
      fullPath: '/prs/$prId/reviews/$reviewId'
      preLoaderRoute: typeof AuthenticatedPrsPrIdReviewsReviewIdRouteImport
      parentRoute: typeof AuthenticatedPrsPrIdRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsClisRoute: typeof AuthenticatedSettingsClisRoute
  AuthenticatedSettingsReposRoute: typeof AuthenticatedSettingsReposRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsClisRoute: AuthenticatedSettingsClisRoute,
    AuthenticatedSettingsReposRoute: AuthenticatedSettingsReposRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedPrsPrIdRouteChildren {
  AuthenticatedPrsPrIdReviewsReviewIdRoute: typeof AuthenticatedPrsPrIdReviewsReviewIdRoute
}

const AuthenticatedPrsPrIdRouteChildren: AuthenticatedPrsPrIdRouteChildren = {
  AuthenticatedPrsPrIdReviewsReviewIdRoute:
    AuthenticatedPrsPrIdReviewsReviewIdRoute,
}

const AuthenticatedPrsPrIdRouteWithChildren =
  AuthenticatedPrsPrIdRoute._addFileChildren(AuthenticatedPrsPrIdRouteChildren)

interface AuthenticatedPrsRouteChildren {
  AuthenticatedPrsPrIdRoute: typeof AuthenticatedPrsPrIdRouteWithChildren
}

const AuthenticatedPrsRouteChildren: AuthenticatedPrsRouteChildren = {
  AuthenticatedPrsPrIdRoute: AuthenticatedPrsPrIdRouteWithChildren,
}

const AuthenticatedPrsRouteWithChildren =
  AuthenticatedPrsRoute._addFileChildren(AuthenticatedPrsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedPrsRoute: typeof AuthenticatedPrsRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedPrsRoute: AuthenticatedPrsRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
